---
# Handler to handle common notifications. Handlers are called by other plays.
# See http://docs.ansible.com/playbooks_intro.html for more information about handlers.

- name: restart memcached
  service: name=memcached state=restarted

- name: restart memcached2
  service: name=memcached2 state=restarted

- name: restart memcached3
  service: name=memcached3 state=restarted

